config/routes.rb
Rails.application.routes.draw do
  root "user#index"
  # resources :user
  get "/register", to: "user#new"
  post "/register", to: "user#create"
  get "/user/:id", to: "user#show", as: "user"
  get "/user/:id/edit", to: "user#edit", as: "edit_user"
  patch "/user/:id", to: "user#update"
  delete "/user/:id", to: "user#destroy", as: "delete_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: { message: "Please enter your first name." }

  validates :last_name, presence: { message: "Please enter your last name." }

  validates :birthday, presence: { message: "Please enter your birthday." }

  validates :gender, presence: { message: "Please choose your gender." }
  
  validates :email, presence: { message: "Please enter your email." }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Invalid email format." }, if: -> { email.present? }
  
  validates :phone, presence: { message: "Please enter your phone number." }
  validates :phone, format: { with: /\A(\+66|0)\d{9}\z/, message: "Invalid phone number format." }, if: -> { phone.present? }
  
  validates :subject, presence: { message: "Please select subject." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthday, :gender, :email, :phone, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegisRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/_regis_form.html.erb
<%# <%= form_with model: @user, url: register_path, class: "register-form" do |f| %> 
<%= form_with model: @user, url: form_url, method: form_method, class: "register-form" do |f| %>
  <div class="form-row">
    <div class="form-group">
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name, id: "firstname" %>
      <% @user.errors[:first_name].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name, id: "lastname" %>
      <% @user.errors[:last_name].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group">
      <%= f.label :birthday, "Birthday" %>
      <%= f.date_field :birthday, max: Date.today.strftime("%Y-%m-%d") , id: "birthday" %>
      <% @user.errors[:birthday].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :gender, "Gender" %>
      <div class="gender-group">
        <%= f.radio_button :gender, "male", id: "male", :checked => true %>
        <%= f.label :male, "Male" %>
        <%= f.radio_button :gender, "female", id: "female" %>
        <%= f.label :female, "Female" %>
      </div>
      <% @user.errors[:gender].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group">
      <%= f.label :email, "Email" %>
      <%= f.email_field :email, id: "email" %>
      <% @user.errors[:email].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :phone, "Phone Number" %>
      <%= f.telephone_field :phone, id: "phone" %>
      <% @user.errors[:phone].each do |message| %>
        <div class="error-message" ><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="select-group">
    <%= f.label :subject, "Subject" %>
    <%= f.select :subject, options_for_select([['Ruby on Rails', 'Ruby on Rails'], ['Java', 'Java'], ['Python', 'Python']], @user.subject), include_blank: "Choose option", id: "subject" %>
    <% @user.errors[:subject].each do |message| %>
        <div class="error-message" ><%= message %></div>
    <% end %>
  </div>

  <%= f.submit submit_text , class: "submit-btn" %>
<% end %>

app/views/user/edit.html.erb
<div class="container">
    <%= link_to "< Back", :back %>
    <h1>Edit User</h1>
    <%= render partial: "regis_form", locals: { 
        form_url: user_path(@user), 
        form_method: :patch, 
        submit_text: "Update" 
    } %>
</div>

app/views/user/index.html.erb
<body>
    <div class="list-container">
        <header class="header">
            <h1>Users</h1>
            <%= link_to "Register", register_path, class: "submit-btn" %>
        </header>
        <main class="user-grid">
            <% @users.each do |user| %>
                <div class="user-card">
                    <h2><%= user.first_name %> <%= user.last_name %></h2>
                    <p><%= user.email %></p>
                    <div class="actions">
                        <%= link_to "Detail", user_path(user), class: "action" %>
                        <%= link_to "Edit", edit_user_path(user), class: "action" %>
                        <%= link_to "Delete", delete_user_path(user), class: "action", data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                        } %>
                    </div>
                </div>
            <% end %>
        </main>
    </div>
</body>

app/views/user/new.html.erb
<div class="container">
    <%= link_to "< Back", :back %>
    <h1>Register Form</h1>
    <%= render partial: "regis_form", locals: { 
        form_url: register_path, 
        form_method: :post, 
        submit_text: "Register" 
    } %>
</div>

app/views/user/show.html.erb
<body>
    <div class="list-container">
        <%= link_to "< Back", root_path %>
        <header class="header">
            <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        </header>
        <div>
            <p><strong>Firstname:</strong> <%= @user.first_name %></p>
            <p><strong>Lastname:</strong> <%= @user.last_name %></p>
            <p><strong>Birthday:</strong> <%= @user.birthday %></p>
            <p><strong>Gender:</strong> <%= @user.gender %></p>
            <p><strong>Email:</strong> <%= @user.email %></p>
            <p><strong>Phone Number:</strong> <%= @user.phone %></p>
            <p><strong>Subject:</strong> <%= @user.subject %></p>
        </div>
    </div>
</body>